services:
  web:
    build:
      context: ./web
      target: deps
    command: npm run dev
    environment:
      - NODE_ENV=development
      # Helps file watching on some host/VM setups
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./web:/app
      # Keep container-installed modules, don't overwrite with empty host dir
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
